---
title: 'Annex IV.2 - STREAM: Auxiliary scripts for the conversion from RCG Landing table to COST CL table'
author: "E. Mantzouni"
date: '`r date()`'
output: word_document
---


```{r compil, eval=F,include=F,cache=F,echo=F,warning=F,message=F,progress=F,verbose=F}
#just a reminder to how compile a docx doc
if(F){
rmarkdown::render("Data.Rmd",c("word_document"))
}
```


#Tools

R, Rstudio and packages.


```{r results='hide', message=FALSE, warning=FALSE}
#R general option:
options(stringsAsFactors = FALSE)

#chunk option
knitr::opts_chunk$set(cache=TRUE,echo=TRUE, warning=FALSE, 
	message=FALSE, fig.height=6,progress=FALSE,verbose=FALSE,
		include=TRUE,dev='png',autodep=FALSE)

#load packages
library(reshape2)
library(reshape)
library(dplyr)
library(knitr)
library(pander)
library(data.table) ##!!
library(COSTcore)
library(COSTdbe)
library(COSTeda)

#pander options
panderOptions('table.split.table', 60)
panderOptions('table.style', 'grid')
panderOptions('table.split.cells', 10)
panderOptions('table.alignment.default', 'left')
panderOptions('table.alignment.rownames', 'right')
panderOptions('decimal.mark', ',')
panderOptions('graph.fontsize', '10')

```


# script 02: *RCG_CL_to_COST_CL* 

This script allow to convert the RCG Landing table into CL COST object

##Settings 

```{r data1}

# set the working directory
myWD <- paste("C:\\Users\\Bitetto Isabella\\OneDrive - Coispa Tecnologia & Ricerca S.C.A.R.L\\MARE22\\STREAM\\FINAL REVISION OF DELIVERABLES\\RCG_to_COST", sep="")

logFilePath <- paste(getwd(), "/log_CL.csv", sep="")
path.data <- getwd()

setwd(myWD)

log=TRUE
  
CL <- read.csv(file="DPS_GSA99_LANDINGS.csv", stringsAsFactors=FALSE,  sep=";")

dataset_proj <- "STREAM project"
  

 fpKey <- function(tab, colIndex, sep = ":-:") {
    key <- tab[, colIndex]
    key <- apply(key, 1, paste, collapse = sep)
    key <- gsub("[[:space:]]", "", key)
    return(key)
 }
 

```

##Input Data

*RCG Datacall format* 


```{r data_in1, echo=F}
pander(head(CL))

```


##Processing tables 

Using some data in the DG MARE Med&BS format :


```{r data2}
 if (log) {
logCl <- CL
logCl$duplicated <- FALSE
logMsg <- ""
} else {
logMsg <- " Consider using the log=TRUE parameter."
}
error <- FALSE


names(CL)[which(tolower(names(CL)) == "flag.country")] <- "vslFlgCtry"
names(CL)[which(tolower(names(CL)) == "flag_country")] <- "vslFlgCtry"

names(CL)[which(tolower(names(CL)) == "year")] <- "year"
names(CL)[which(tolower(names(CL)) == "quarter")] <- "quarter"
names(CL)[which(tolower(names(CL)) == "month")] <- "month"
names(CL)[which(tolower(names(CL)) == "area")] <- "area"
names(CL)[which(tolower(names(CL)) == "species")] <- "taxon"

names(CL)[which(tolower(names(CL)) == 
                  "fishing.activity.category.national")] <- "foCatNat"
names(CL)[which(tolower(names(CL)) == "fac_national")] <- "foCatNat"

names(CL)[which(tolower(names(CL)) == 
                  "fishing.activity.category.european.lvl.6")] <- "foCatEu6"
names(CL)[which(tolower(names(CL)) == "fac_ec_lvl6")] <- "foCatEu6"

names(CL)[which(tolower(names(CL)) == "harbour")] <- "harbour"

names(CL)[which(tolower(names(CL)) == "official.landings.weight")] <- "landWt"
names(CL)[which(tolower(names(CL)) == "official_landings_weight")] <- "landWt"

names(CL)[which(tolower(names(CL)) == "official.landings.value")] <- "landValue"
names(CL)[which(tolower(names(CL)) == "official_landings_value")] <- "landValue"


## primary keys & fields

clPk <- c("vslFlgCtry", "year", "quarter", "month", "area", "taxon", 
          "foCatNat", "foCatEu6")
clOther <- c("landWt", "landValue")

# check fields
allFields <- c(clPk, clOther)
missingFields <- allFields[! allFields %in% names(CL)]
if (length(missingFields) > 0) {
stop("Missing fields : ", paste(missingFields, collapse = ", ", sep=""))
}

 clPkV <- fpKey(CL, clPk)
clPkVDup <- clPkV %in% clPkV[duplicated(clPkV)]

# test integrity
if (any(clPkVDup)) {
if (log) {
logCl$duplicated <-  fpKey(CL, clPk)
}
  
  
if (bad.rm) {
message("Integrity problem for CL, ", sum(clPkVDup),
" row(s) removed.", logMsg)
CL <- CL[! clPkVDup,]
} else {
error <- TRUE
message("Integrity problem for CL, ", sum(clPkVDup),
" row(s) concerned.", logMsg)
}
}



if (log) {
if (missing(logFilePath)) {
logFilePath <- tempfile(fileext = ".csv")
}
write.table(logCl, file=logFilePath, row.names = FALSE, sep=";")
message("Log file: ", logFilePath)
}
if (error) {
stop("Stop on reported errors.")
}


# formating

CL$taxon <- unlist(lapply(CL$taxon, function(x)
paste(toupper(substring(x, 1, 1)), tolower(substring(x, 2)), sep="")))


## df
clDf <- data.frame(
landCtry=NA,
vslFlgCtry=CL$vslFlgCtry,
year=CL$year,
quarter=CL$quarter,
month=CL$month,
area=CL$area,
rect=NA,
subRect=NA,
taxon=CL$taxon,
landCat=NA,
commCatScl=NA,
commCat=NA,
foCatNat=CL$foCatNat,
foCatEu5=NA,
foCatEu6=CL$foCatEu6,
harbour=CL$harbour,
vslLenCat=NA,
unallocCatchWt=NA,
misRepCatchWt=NA,
landWt=CL$landWt,
landMult=NA,
landValue=CL$landValue,
stringsAsFactors=FALSE)

write.table(clDf, file.path(path.data,  "SDEF CL data.csv"), sep=";", row.names = FALSE)

costCL = clData(cl=clDf)
saveRDS(costCL, "costCL.rds")
  
```


##Output

*CL COST object*


```{r data_10, echo=F, eval=T}
    
head(costCL)

options(warn=0)

```



