---
title: "Annex III.2 - STREAM: Auxiliary scripts for the conversion from the SDEF format to DG MARE Med&BS Data Call: Raising of the length distributions by ID of the discards"
author: "E. Mantzouni"
date: "`r date()`"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r results='hide', message=FALSE, warning=FALSE}
#R general option:
options(stringsAsFactors = FALSE)

options(warn=0)

options(scipen = 999) # disable scientific notation

#chunk option
knitr::opts_chunk$set(cache=TRUE,echo=TRUE, warning=FALSE, 
	message=FALSE, fig.height=6,progress=FALSE,verbose=FALSE,
		include=TRUE,dev='png',autodep=FALSE)

#load packages

library(COSTcore)
library(COSTeda)
library(COSTdbe)
library(tidyr)
library(dplyr)
library(data.table)
library(knitr)

```



##Settings

```{r data1  , message=FALSE}

path_in <- paste("C:\\Users\\Bitetto Isabella\\OneDrive - Coispa Tecnologia & Ricerca S.C.A.R.L\\MARE22\\STREAM\\FINAL REVISION OF DELIVERABLES\\SDEF_to_DG_MARE_MedBS", sep="") 
setwd(path_in)

```

```{r "setup", include=FALSE}
opts_knit$set(root.dir = path_in)
```

##Input Data

Validated csData , ceData, and clData 

```{r data_in1,warning=FALSE}
load("fri-TEST.Rdata")

head(fri_cs1@hh$foCatEu5)
head(fri_cl1@cl$foCatEu5)
head(fri_cev@ce$foCatEu5)

fri_strD1 <- strIni(timeStrata="quarter", techStrata = "foCatEu5",
                    spaceStrata = "area")

fri_strD1

fri_csc <- csDataCons(fri_cs1, fri_strD1)
fri_clc <- clDataCons(fri_cl1, fri_strD1)
fri_cec <- ceDataCons(fri_cev, fri_strD1)


head(fri_csc )
head(fri_clc)
head(fri_cec)

# extract COUNTRY  and YEAR
COUNTRY<-unique(fri_cl1@cl$landCtry)
YEAR=unique(fri_cl1@cl$year)

```


DG MARE Med&BS DISCARDS Table template

```{r data_in3}

dis.temp2<- read.table("xxx_DISCARDS.csv",sep=",",header=T)
names(dis.temp2)
```

```{r data_in4}

fishery<- read.table("communicationTable_for_fishery.csv",sep=";",
                     header=T)
head(fishery)
```


Auxiliary table: species_DIS.csv


```{r data_in5}

# species file : selected species with FAO three alpha code

sel_spe <-read.table("species_DISCARDS.csv",sep=";",header=T)
head(sel_spe)

```

## Data analysis- raising

Analysis by stock
```{r loop by stock, warning=F, message=F}

for (i in 1:dim(sel_spe)[1]) {
  
  STK<- sel_spe$SPECIES[i]
  
  AREA <- sel_spe$GSA[i]

    fri_csc1<- subset(fri_csc, space==sel_spe$GSA[i],table="ca",link=T)
  fri_clc1<- subset(fri_clc, space==sel_spe$GSA[i],table="cl")
  
    fri_cec1<- subset(fri_cec, space==sel_spe$GSA[i],table="ce")

  # The first step is to create the empty object, that will be given 
    # the appropriate values for the descritor  fields.
  
  DIS_dbe <- dbeObject(desc= paste(STK, AREA,"Discards", sep="_"),
                       species=STK,
                       catchCat="DIS",
                       strataDesc=fri_strD1,
                       methodDesc="analytical"
                       )

  if (sel_spe$type[i]=="landings" ) {
  
  DIS_dbe <- totVolume(DIS_dbe,fri_csc1,fri_cec1, fri_clc1,
      type=sel_spe$type[i],val="nAtLength",landSpp=sel_spe$landSpp[i])
  } else {
     DIS_dbe <- totVolume(DIS_dbe,fri_csc1,fri_cec1, type=sel_spe$type[i],
                          val="nAtLength")
  }


  # totalW\$estim : total weight, 
aa <-DIS_dbe@totalW$estim 
  
aa$value<- aa$value/1000 # tons

aa<- rename(aa, "totalW"=value)
  # lenStruc\$estim : numbers-at-length estimates, 

  bb<- DIS_dbe@lenStruc$estim
  
  bb$length=as.numeric(bb$length)
  
   # define LCs and UNIT len 
 UNIT <- as.character( unique(fri_csc@ca$lenCode[fri_csc@ca$spp==STK]) )
  
 if (UNIT %in% c("mm", "MM")& sel_spe$LC_RANGE[i]==10) {
 bb$length<-as.numeric(bb$length)/10
 UNIT1<-"cm"
 }
  
  if (UNIT %in% c("mm", "MM") & sel_spe$LC_RANGE[i]==1) {
 bb$length<-as.numeric(bb$length)
 UNIT1<- "mm"
  }
 
   if (UNIT %in% c("mm", "MM")& sel_spe$LC_RANGE[i]==5) {
 bb$length<-as.numeric(bb$length)/10
 UNIT1<-"cm"
  }
 
   if (UNIT %in% c("cm", "CM") ) {
 bb$length<-as.numeric(bb$length)
 UNIT1<- "cm"
  }
   bb$length<- plyr::round_any( bb$length,1,floor)
  
  bb$value<- bb$value/1000 # '000 ind
  
  ab=left_join(bb,aa ,by = c("time", "space", "technical"))
  
   ab<- ab %>% separate(technical, c("gear","FISHERY", "VL","MESH_SIZE_RANGE"), 
                        sep = "_",remove=T)
  
  ab$length<- as.numeric(as.character(ab$length))
  
  ab<- ab%>% group_by(time,   space , gear  ,FISHERY, VL,MESH_SIZE_RANGE  ) %>%
    mutate(minlc=min(length,na.rm=T),maxlc=max(length,na.rm=T))
  
   # matrix with all combinations of "time"   "space"  "gear"   "VL"     
  # "length" ,"MESH_SIZE_RANGE"
 
      dt <- as.data.table(ab)
  
   dt[,c(1:6)][is.na(dt[,c(1:6)])]<- -1
  
  seq_l <-  seq(0, max(dt$length,na.rm = T), by = 1) # 
  
  dt$id<- paste(dt$time,dt$space,dt$gear,dt$FISHERY,dt$VL,
                dt$MESH_SIZE_RANGE,sep=":")

  dt1<- dt[, list(length = seq_l), by = id]
  
  dt1<- dt1 %>% separate(id, c("time", "space", "gear", "FISHERY","VL",
                               "MESH_SIZE_RANGE"), sep = ":")
    
  
  # ab[,`1:6]: NA-->-1  
ab<- ab %>%ungroup()%>% mutate_at(vars(c(time:MESH_SIZE_RANGE) ), 
          funs( ifelse( is.na(.), -1, .) ) )

  
  dt2<- left_join(dt1,ab)
  dt2$stock<- STK
  
  ##
  
dt3 <- data.table::dcast(dt2,as.formula(paste(paste(names(dt2)[! names(dt2) %in%
                  c("length","value")], collapse='+'), "length", sep="~")), 
                  value.var = "value")
  
  dt3=dt3[complete.cases(dt3[,c(7:9)]), ]
  
dt3 <- dt3 %>% separate(time, c("Year","Quarter")," - ")

  dt3$MESH_SIZE_RANGE<-as.character(dt3$MESH_SIZE_RANGE)


  # numbers at LC : NA-->0  
dt3<- dt3 %>% mutate_at(vars( -(Year:stock) ), 
          funs( if_else( is.na(.), 0, .) ) )

  DISCARDS <- data.frame(
    
    ID = NA , 
    COUNTRY = COUNTRY , 
    YEAR = YEAR , 
    QUARTER =dt3$Quarter, 
    VESSEL_LENGTH = dt3$VL,
    GEAR = dt3$gear,
MESH_SIZE_RANGE = dt3$MESH_SIZE_RANGE,
   FISHERY= dt3$FISHERY  , 
    AREA = sel_spe$GSA[i],
    SPECON = "",
    SPECIES = STK , 
    DISCARDS = dt3$totalW ,
    UNIT = UNIT1
  )
  
  DISCARDS<-left_join(DISCARDS,dt3[,-c(1,3,8:11)],by=c( "QUARTER"  ="Quarter" , 
        "GEAR"="gear" ,  "VESSEL_LENGTH" = "VL"  ,"MESH_SIZE_RANGE","FISHERY" ))
  
  # take care of number of Length classes (max is 100 acc. to JRC template)
  zz<-dim(DISCARDS[-c(1:13)])[2]
  names(DISCARDS)[-c(1:13)]<- paste("LENGTHCLASS",seq(0,zz-1,1),sep="")
  
  if(zz>=100){
    DISCARDS$LENGTHCLASS100_PLUS<- rowSums(DISCARDS[,!1:113],na.rm = T)
     DISCARDS<-DISCARDS %>% select(ID:LENGTHCLASS99,LENGTHCLASS100_PLUS)
  }

   # FISHERY to DG MARE Med&BS specification
  DISCARDS$FISHERY <- fishery$SDEF_codification[match(DISCARDS$FISHERY ,
                                    fishery$DGMARE_Med_BS_codification)]
  
  # species to FAO three aòpha code and set ID (COUNTRY, AREA, GEAR, 
  # VESSEL_LENGTH,  MESH_SIZE_RANGE,QUARTER, SPECIES)
  
dis.tab <-DISCARDS %>% mutate(SPECIES=sel_spe$SPE[match(SPECIES,sel_spe$SPECIES)],
           ID = paste(COUNTRY, AREA, GEAR,FISHERY, VESSEL_LENGTH, 
                      MESH_SIZE_RANGE,YEAR, QUARTER, SPECIES, sep = "_"))
  
 dis.temp2<-bind_rows(dis.temp2,dis.tab)

  # col after 13: set -1 or NA to 0 
dis.temp2[,-c(1:13)][is.na(dis.temp2[,-c(1:13)])] <- 0

dis.temp2<-setDT(dis.temp2)
for (jj in c(14:114)) set(dis.temp2, i = which(dis.temp2[[jj]]==-1), j = jj, v = 0)

dis.temp2<-setDF(dis.temp2)
  
}

```

##Output

```{r data_ou1}

write.table(format(dis.temp2,digits=3,scientific=F), 
        file = "DISCARDS.csv",row.names=FALSE,sep=";",na="-1")

head(dis.temp2)

  
```

